### PR TITLE
Random code improvements

### PR DESCRIPTION
**Pull request by tweakimp**
Remove unnecessary code, use fstring and list comprehension, rearrange comments

### CODE REVIEW

**Comment by tweakimp** [comment]
For Hackathon :)

**Comment by WalJT** [comment]
Hi,
Thanks for your input, I've created a new branch (issue40-tweakimp-master) to have a look at the changes and it's got my approval anyway.

**Comment by mjancen** [comment]
Looks good to me, thanks for the cleanup! This PR also resolves issue #38.

**Review by m-squared96 — CHANGES_REQUESTED** [review]
The code looks really good, really appreciate the use of list generators and fstrings to tidy up some areas. Could you replace the type hinting in trajectory.py though? Specifically in the function/method signatures.

**Comment by tweakimp** [comment]
Do you mean to remove the None type hint?
I think it looks cleaner to rmove the `-> None` and imply that we dont return anything.

**Comment by m-squared96** [comment]
I hear what you're saying, but I'd rather keep the `-> None` as it's explicit about what's returned and consistent then with the rest of the code. @mjancen @WalJT  any thoughts?

**Comment by tweakimp** [comment]
Are there any other changes you meant?

**Comment by m-squared96** [comment]
Nope, it's generally very nice code and I'm very happy with the rest of it.

**Comment by mjancen** [comment]
TBH I don't mind either format but I get what you mean @m-squared96

**Comment by m-squared96** [comment]
Yeah, I don't mean to come across as too picky @tweakimp just trying to keep it all consistent

**Comment by tweakimp** [comment]
What about `__init__` functions? They never return anything.

**Comment by m-squared96** [comment]
Usually not but it can happen, we have updates down the line that (might) require `__init__` functions to return values

**Comment by mjancen** [comment]
From what I've read I'm not sure if returning from `__init__` makes sense, but that's a discussion for another day

**Review by m-squared96 — APPROVED** [review]

**Comment by WalJT** [comment]
> I hear what you're saying, but I'd rather keep the `-> None` as it's explicit about what's returned and consistent then with the rest of the code. @mjancen @WalJT any thoughts?

I don't really have an opinion one way or the other about the `-> None` hint... I'll just go with the flow to keep the code consistent.

**Pull request merged**
