### PR TITLE
FOV Adaptation Fixes

### PR DESCRIPTION
**Pull request by m-squared96**
Solution to #55 

Changes limited to trajectory.py, include breaking up PSP classes into more modular method components. Was able to push some code up to parent class, potentially more could be added up there to avoid repitition.

@mjancen pay particular attention to PhaseSpaceParent.toggle_nullclines() as I've had to add a couple of lines of code to make nullclines persistent after FOV changes.

### CODE REVIEW

**Comment by m-squared96** [comment]
Original: Solution to #56 in here too
Edit: This is actually untrue, home button issue not solved as yet.

**Comment by m-squared96** [comment]
Just realised I overlooked testing the fixed points, they don't get the same treatment as the nullclines with the new FOV code. I'll amend that and commit

**Review by WalJT — APPROVED** [review]
Just got around to looking at this now... It's got my stamp of approval anyway.

**Comment by WalJT** [comment]
Also, I've made some changes to the snap build, and want to clean up the files in this repo accordingly. I'll wait 'till this gets merged, then spend some time on that over a weekend.

**Review by mjancen — APPROVED** [review]

**Comment by Salemsa89** [comment]
- [ ] https://github.com/m-squared96/PyPLANE/commit/2db4049df48b1b41f68f69e2fb33a21a11e4b3f0#diff-f962450704f44671e3ff5523ec3decefa265a10767bc5670ee642cfc774ff711

**Pull request merged**
