### PR TITLE
Getting ready to push "beta" snaps from the `dev` branch

### PR DESCRIPTION
**Pull request by WalJT**
I've made quite a few changes to set up the repo for building snaps. The most significant change is renaming the `source` directory to `PyPLANE`, and using it to build a Python package called PyPLANE. The app can be executed without installing this package by using the script `run` in the root of the project. The script `bin/run` is executed by the snap. There's also a `snapcraft.yaml` file, and the `snap/gui` directory that contains the .desktop file an the icon. Should all merge without any problems, as I've already merged in the latest changes from `dev`.

Once stuff has been merged I think we're ready to publish a beta snap. I already have a snapcraft developer account, and would be happy to use it, but we could also create a shared account just for PyPLANE If you think that's a better idea...

### CODE REVIEW

**Comment by mjancen** [comment]
Just on the snapcraft account thing, how do projects usually manage it? Is there usually a single person managing the snap package, or is it some package account that the whole team has direct access to?

**Comment by WalJT** [comment]
From what I can tell a lot of open source projects (eg. Glimpse, Keepassxc, 0ad) have one person in charge of the snap. The bigger ones have a team account. (Blender is published by the blender foundation, Spotify by "spotify", VS Code by a team within Microsoft). I'd be okay doing it either way.

Also seems like Popey packages a lot of stuff...

**Comment by m-squared96** [comment]
So the app works grand when I run "python run", but when I try and run the run file in bin/ it looks for a PyPLANE module in the Python env. So to create the snap we need to build some kind of Python environment with PyPLANE installed as a module of some kind, right? 
    1. Is the above correct?
    2. If so, how do we automate this to facilitate automatic snap builds?
    3. How do we structure the project to facilitate app builds for architectures other than snaps? I'm thinking specifically for Windows-compatible app builds.

**Comment by WalJT** [comment]
1. Yep...
2. Snapcraft does that automatically, effectively running `setup.py install`
3. Shouldn't be too hard to work with something like pyinstaller or pyoxidizer with the current structure... I might actually try and see if I can build on Windows with pyinstaller, now that you mention it.

**Review by m-squared96 — APPROVED** [review]
Looks fine to me, I don't know much about this kind of thing but I'm confident seeing as you can build both snaps and Windows installs from this branch.

**Comment by mjancen** [comment]
Approved, merge that boi. Also Julian you can manage the snapcraft account for now, might have a look at it later

**Pull request merged**
