### PR TITLE
Feature/iss77 time: Proposal 2

### LINKED ISSUE #77: Single-Dimension vs Time Trajectories
The user should be able to select a trajectory plotted on the two-dimensional interface (which would display x(t) vs y(t)) and show any/all of the below plotting options:
a. t vs x(t)
b. t vs y(t)
c. t vs x(t) vs y(t)

### PR DESCRIPTION
**Pull request by m-squared96**
Second attempt at TCA. Draft

Pros:
1. Far more functionality and flexibility
2. Multiple TCA plots can be spawned simultaneously, allowing for different types of analysis and including components from multiple trajectories on the same plot

Cons:
1. More code
2. Kinda complex, especially compared to #89 

Known issues:
1. Can't turn off annotations yet
2. Needs figure labels
3. Need GUI labels

### CODE REVIEW

**Comment by WalJT** [comment]
I would go with this solution over #89

**Comment by m-squared96** [comment]
I've stood still on this for too long. Let's merge this as it is and address the issues that follow as they come.

**Review by mjancen — CHANGES_REQUESTED** [review]
The TCA class is duplicated in analysis.py and ui_main_window.py.

Other than that, there are a few changes that I would like to make, but I'll make them in a separate branch and we can merge this branch once the above is addressed.

For reference, changes I intend to make:
* Combine "plot_separately" and "plot_together" variable into one variable that takes values of an enum class.
* Combine the tca_tvs* functions because that is some [WET-ass code](https://www.softwareyoga.com/is-your-code-dry-or-wet/)

**Review by mjancen — APPROVED** [review]
Removed the duplicate TCAWindow class from ui_main_window, so I think it's ready to merge.

**Pull request merged**
